### ISSUE TITLE
Missing input validation: unchecked payload length when decoding CBOR text string labeled items

### ISSUE THREAD

**Issue by br4ndst3r** [yuichitk/libcsuit#15]
### Issue:
The suit_payload_t array inside the suit_payloads_t struct can be overflowed by the function suit_decode_envelope_from_item.
A missing check of suit_payloads_t.len allows writing beyond the suit_payloads_t.payload array boundary.
This occurs at the condition [suit_manifest_decode.c:1032](https://github.com/yuichitk/libcsuit/blob/master/src/suit_manifest_decode.c#L1032), where values are written to the payload at position payloads.len and payloads.len is increased.

### Reproduction:
The examples/suit_manifest_parser_main_psa.c file can be used for reproduction.
Therefore replace the given manifest with this manifest: [crash.zip](https://github.com/yuichitk/libcsuit/files/9047386/crash.zip)
Execution should lead to a Segmentation fault.

### Affects:
master (commit 6fdbecd0c2e2389a6a169f897b9aef35eee626d9).
At a quick glance it seems that there are more length checks missing for arrays in typedefs of [suit_common.h](https://github.com/yuichitk/libcsuit/blob/master/inc/csuit/suit_common.h).

### Suggested patch:
#16: Check if payloads.len >= SUIT_MAX_ARRAY_LENGTH before accessing payload array items.

**Comment by hisanak** [comment]
Thank you for your bug report. We'll quickly check and fix other related bugs.

**Comment by hisanak** [comment]
Fixed also related bugs with [this commit](https://github.com/yuichitk/libcsuit/commit/c8367a54ecafc27dfa98a0ec24f5f7a2f988b1a7).
